[2023-11-29 18:39:28,296] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-29 18:39:30,010] [WARNING] [runner.py:203:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-11-29 18:39:30,010] [INFO] [runner.py:570:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None eval.py --data_path ./data/alzheimer/HCP_WM --tensorboard_path ./eval_results --deepspeed --per_device_train_batch_size 128 --per_device_eval_batch_size 128 --num_train_epochs 500 --test_env 0 --input_dim 268 --hidden_dim 268 --mlp_dim 1072 --num_heads 4 --layers 12 --seq_len 64 --downsample_rate 1 --model_name_or_path Vanilla_FT_keep_5 --before --output_dir ./eval_results
[2023-11-29 18:39:31,816] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-29 18:39:33,487] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.13.4-1+cuda11.7
[2023-11-29 18:39:33,487] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.13.4-1
[2023-11-29 18:39:33,487] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.13.4-1
[2023-11-29 18:39:33,487] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2023-11-29 18:39:33,487] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7
[2023-11-29 18:39:33,487] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2023-11-29 18:39:33,487] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.13.4-1
[2023-11-29 18:39:33,487] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-11-29 18:39:33,487] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-11-29 18:39:33,487] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-11-29 18:39:33,487] [INFO] [launch.py:163:main] dist_world_size=1
[2023-11-29 18:39:33,487] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-11-29 18:39:35,823] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Namespace(data_path='./data/alzheimer/HCP_WM', model_name_or_path='Vanilla_FT_keep_5', per_device_train_batch_size=128, per_device_eval_batch_size=128, learning_rate=5e-05, weight_decay=0.0, num_train_epochs=500, gradient_accumulation_steps=1, lr_scheduler_type=<SchedulerType.COSINE: 'cosine'>, num_warmup_steps=0, output_dir='./eval_results', seed=1234, local_rank=0, gradient_checkpointing=False, offload=False, zero_stage=0, lora_learning_rate=0.0005, enable_tensorboard=False, tensorboard_path='./eval_results', hidden_dim=268, input_dim=268, mlp_dim=1072, num_heads=4, layers=12, seq_len=64, dropout_rate=0.0, downsample_rate=1, test_env=0, before=True, skip_5=False, update=False, num_samples_per_class=50, deepspeed=True, deepspeed_config=None, deepscale=False, deepscale_config=None, deepspeed_mpi=False)
[2023-11-29 18:39:38,302] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-29 18:39:38,302] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
device cuda:0
--------------Test Env:  0 -----------------
Loading data from ./data/alzheimer/HCP_WM/Scan1/processed_data.npy and ./data/alzheimer/HCP_WM/Scan1/processed_labels.npy
Loading data from ./data/alzheimer/HCP_WM/Scan2/processed_data.npy and ./data/alzheimer/HCP_WM/Scan2/processed_labels.npy
No intersection
load model from Vanilla_FT_keep_5/pytorch_model_before_ft.bin
=========> Evaluation Result <=========
len eval set 10254
Overall Accuracy:  0.38638580066315587
Per Class Accuracy:  {5: 0.9991472427515634, 13: 0.0855106888361045, 11: 0.026128266033254157, 2: 0.004750593824228029, 17: 0.07482185273159145, 15: 0.0344418052256532, 4: 0.0498812351543943, 9: 0.24584323040380046, 7: 0.009501187648456057}
len train set 11184
=========> Training Result <=========
Overall Accuracy:  0.908530042918455
Per Class Accuracy:  {5: 0.9997317596566524, 9: 0.7982832618025751, 13: 0.8036480686695279, 17: 0.9130901287553648, 2: 0.8186695278969958, 7: 0.9967811158798283, 4: 0.8272532188841202, 15: 0.8476394849785408, 11: 0.898068669527897}
[2023-11-29 18:39:51,515] [INFO] [launch.py:347:main] Process 3617990 exits successfully.
